services:
    backend1:
        build:
            context: ./backend1
            dockerfile: Dockerfile.dev
        ports:
            - "3001:3000"
        networks:
            custom_net:
                ipv4_address: 172.30.0.2

    backend2:
        build:
            context: ./backend2
            dockerfile: Dockerfile.dev
        ports:
            - "3002:3000"
        networks:
            custom_net:
                ipv4_address: 172.30.0.3

    load-balancer:
        build:
            context: ./load-balancer
            dockerfile: Dockerfile.dev
        ports:
            - "80:80"
        networks:
            custom_net:
                ipv4_address: 172.30.0.4

networks:
    custom_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.30.0.0/16
